<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.5" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.5" PrivateAssets="all" />
		<PackageReference Include="Blazored.FluentValidation" Version="2.1.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\InventoryManagement.Shared\InventoryManagement.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Features\Products\a\" />
	</ItemGroup>

</Project>
