@InventoryManagement.API_HostAddress = http://localhost:5079

GET {{InventoryManagement.API_HostAddress}}/api/Categories/
Accept: application/json

###
POST {{InventoryManagement.API_HostAddress}}/api/Categories
Content-Type: application/json
{
  "name" :"Books"
}
###
PUT {{InventoryManagement.API_HostAddress}}/api/Categories/2
Content-Type: application/json
{
  "name" :"Books days"
}
###
Delete {{InventoryManagement.API_HostAddress}}/api/Categories/2
Content-Type: application/json

###
PUT {{InventoryManagement.API_HostAddress}}/api/Categories/3/activate
Content-Type: application/json

###
PUT {{InventoryManagement.API_HostAddress}}/api/Categories/3/deactivate
Content-Type: application/json

###
GET {{InventoryManagement.API_HostAddress}}/api/Products/
Accept: application/json
api-version : 2

####
GET {{InventoryManagement.API_HostAddress}}/api/Products/7B50D616-6D51-4BC4-B8A2-990B6C2CCCDC
Accept: application/json
api-version : 2